version: '3.8'
services:
  app:
    container_name: dublimator-pane-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped